classDiagram

    class AppMachine {
        - instance : AppMachine
        - constructor() void
        + getInstance() AppMachine

        - currentState : AppState
        + changeState(newState : STATE) void
        + run() void
    }

    class AppState {
        <<interface>>
        + onEnter() void
        + onExecute() void
        + onExit() void
    }

    class LoginState {
    }
    class LogoutState {
    }
    class ManagerDashboardState {
    }
    class CustomerDashboardState {
    }
    class AddItemState {
    }
    class ViewOrdersState {
    }
    class BrowseMenusState {
    }
    class ViewCartState {
    }
    class AddItemToCartState {
    }
    class CheckoutState {
    }
    class PaymentProcessingState {
    }
    class OrderConfirmationState {
    }

    AppState <|.. LoginState
    AppState <|.. LogoutState
    AppState <|.. ManagerDashboardState
    AppState <|.. CustomerDashboardState
    AppState <|.. AddItemState
    AppState <|.. ViewOrdersState
    AppState <|.. BrowseMenusState
    AppState <|.. ViewCartState
    AppState <|.. AddItemToCartState
    AppState <|.. CheckoutState
    AppState <|.. PaymentProcessingState
    AppState <|.. OrderConfirmationState

    class STATE {
        <<enumeration>>
        LOGIN
        LOGOUT
        MANAGER_DASHBOARD
        CUSTOMER_DASHBOARD
        ADD_ITEM
        VIEW_ORDERS
        BROWSE_MENUS
        VIEW_CART
        ADD_ITEM_TO_CART
        CHECKOUT
        PAYMENT_PROCESSING
        ORDER_CONFIRMATION
    }

    class StateMapper {
        + stateMap : Map~STATE, AppState~
        + getState(stateName : STATE) AppState
    }

    StateMapper "1" --* "*" AppState

    AppMachine "1" -- "1" AppState
    AppMachine -- StateMapper

    class ItemUI {
        + addItem(name : string, basePrice : int, category : String) void
    }

    ItemUI -- ItemRepository
    ItemUI -- CategoryRepository
    ItemUI -- CustomizationAddonRepository

    class MenuUI {
        + displayMenus(menus : List~Menu~) void
        + createMenu(title : string, description : string, items : List~Item~) Menu
    }

    MenuUI -- MenuRepository

    class CartUI {
        + displayCart(cart : Cart) void
        + addItemToCart(item : Item, quantity : int) void
        + removeItemFromCart(item : Item) void
        + updateItemQuantityInCart(item : Item, quantity : int) void
    }

    CartUI -- Cart

    class Cart {
        - instance : Cart
        - constructor() void
        + getInstance() Cart
        + items : Map~Item, int~
        + addItem(item : Item, quantity : int) void
        + removeItem(item : Item) void
        + updateItemQuantity(item : Item, quantity : int) void
        + calculateTotal() int
    }

    Cart "1" --* "*" Item

    class CheckoutManager {
        - instance : CheckoutManager
        - constructor() void
        + getInstance() CheckoutManager
        - placeOrderEvent : PlaceOrderEvent
        + checkout(customerName : string, orderType : ORDER_TYPE, paymentMethod: string) void
    }

    class PlaceOrderEvent {
        + constructor() void
    }

    CheckoutManager "1" --* "1" PlaceOrderEvent

    CheckoutManager -- Cart
    CheckoutManager -- PaymentProcessor

    class Item {
        + name : string
        + basePrice : int
        + category : Category
    }

    class ItemFactory {
        + createItem(name : string, basePrice : int, category : Category) Item
    }

    ItemFactory -- Item

    class ItemRepository {
        - items : List~Item~
        + addItem(item : Item) void
        + getItemsByCategory(category : Category) List~Item~
        + getItemByName(name : string) Item | null
    }

    ItemRepository "1" --* "*" Item

    class Category {
        + name : string
        + parent : Category
    }

    class CategoryFactory {
        + createCategory(name : string, parent : Category) Category
    }

    CategoryFactory -- Category
    CategoryFactory -- CategoryRepository

    class CategoryRepository {
        - categories : List~Category~
        + addCategory(category : Category) void
        + getCategoryByName(name : string) Category | null
    }

    CategoryRepository "1" --* "*" Category

    Category "1" --o "*" Item
    Category "*" --o "1" Category

    class ORDER_TYPE {
        <<enumeration>>
        DINE_IN
        TAKEOUT
        DELIVERY
    }

    class Order {
        - id : string
        + customerName : string
        + date : Date
        + totalAmount : int
        + tip : int
        + status : string
        + orderType : ORDER_TYPE
    }

    class OrderItem {
        + item: Item
        + order: Order
    }

    Order "1" --o "*" OrderItem
    Item "1" --o "*" OrderItem

    class Menu {
        + title : string
        + description : string
        + items : List~Item~
    }

    class MenuFactory {
        + createMenu(title : string, description : string, items : List~Item~) Menu
    }

    MenuFactory -- Menu

    class MenuRepository {
        - menus : List~Menu~
        + addMenu(menu : Menu) void
        + getAllMenus() List~Menu~
    }

    Menu "1" --o "*" Item

    class CustomizationAddon {
        + name : string
        + item : Item
        + isMandatory : bool
        + options : List~CustomizationOption~
    }

    class CustomizationAddonRepository {
        - addons : List~CustomizationAddon~
        + addAddon(addon : CustomizationAddon) void
        + getAddonsForItem(item : Item) List~CustomizationAddon~
    }

    Item "1" --o "*" CustomizationAddon

    class CustomizationOption {
        + value : string
        + deltaPrice : int
    }

    CustomizationAddon "1" --o "*" CustomizationOption

    class Event ~EventPayload~ {
        <<abstract>>
        # listeners : List~Listener~
        # constructor() void
        + subscribe(listener : Listener) void
        + unsubscribe(listener : Listener) void
        + notify(data : EventPayload) void
    }

    class EventPayload {
        <<interface>>
    }

    Event ..> EventPayload

    class EventFactory {
        - instance : EventFactory
        - constructor() void
        + getInstance() : EventFactory

        - eventMap : Map~string, Event~
        + getEvent(eventName : string) : Event~
    }

    EventFactory "1" --* "*" Event

    class Listener ~EventPayload~ {
        <<interface>>
        + update(data : T) void
    }

    PlaceOrderEvent ..|> Event~Order~

    class PlaceOrderListener {
        <<interface>>
        + update(data : PlaceOrderPayload) void
    }

    class PlaceOrderPayload {
        + order : Order
    }

    PlaceOrderEvent -- PlaceOrderListener
    PlaceOrderListener ..> PlaceOrderPayload
    PlaceOrderEvent ..> PlaceOrderPayload

    class Kitchen {
        - instance : Kitchen
        - constructor() void
        + getInstance() Kitchen

        - queue : List~Order~

        - addOrder(order : Order) void
        - processNextOrder() Order
        - notifyOrderReady(order : Order) void

        + update(data : PlaceOrderPayload) void
    }

    Kitchen --|> PlaceOrderListener : implements
    Kitchen -- EventFactory

    class PaymentProcessor {
        - instance : PaymentProcessor
        - constructor() void
        + getInstance() PaymentProcessor
        - paymentCredentials : UserPaymentCredentials
        + feedPaymentCredentials(credentials : UserPaymentCredentials) void
        + processPayment(order : Order, paymentMethod : string) Payment
    }

    class UserPaymentCredentials {
        <<interface>>
    }

    class CreditCardCredentials {
        + cardNumber : string
        + cardHolderName : string
        + expiryDate : string
        + cvv : string
    }

    class DigitalWalletCredentials {
        + walletId : string
        + provider : string
    }

    UserPaymentCredentials <|.. CreditCardCredentials
    UserPaymentCredentials <|.. DigitalWalletCredentials

    PaymentProcessor "1" --* "*" UserPaymentCredentials

    class PaymentCredentialsValidator {
        + static validate(credentials : UserPaymentCredentials) bool
    }

    class CreditCardValidator {
        + static validate(credentials : CreditCardCredentials) bool
    }

    class DigitalWalletValidator {
        + static validate(credentials : DigitalWalletCredentials) bool
    }

    class PaymentValidatorFactory {
        + static getValidator(paymentMethod: string) PaymentCredentialsValidator
    }

    CreditCardValidator ..> CreditCardCredentials
    DigitalWalletValidator ..> DigitalWalletCredentials

    PaymentProcessor -- PaymentCredentialsValidator
    PaymentCredentialsValidator ..> CreditCardValidator
    PaymentCredentialsValidator ..> DigitalWalletValidator

    PaymentValidatorFactory ..> PaymentCredentialsValidator

    class Payment {
        + order : Order
        + transactionId : string
        + amount : int
        + method : string
        + status : string
    }

    class PaymentMethod {
        <<interface>>
        + pay(amount : int) int
    }

    class CreditCard {
        + pay(amount : int) int
    }

    class CashPayment {
        + pay(amount : int) int
    }

    class DigitalWallet {
        + pay(amount : int) int
    }

    PaymentMethod <|.. CreditCard
    PaymentMethod <|.. CashPayment
    PaymentMethod <|.. DigitalWallet

    PaymentProcessor -- Payment
    Order "1" --o "1" Payment

    class Discount {
        <<interface>>
        + calculate(amount : int) int
    }

    class Repository ~T K~ {
        <<interface>>
        + add(item : T) void
        + get(id : K) T | null
        + getAll() List~T~
        + remove(id : K) void
    }

    Repository <|.. ItemRepository~Item string~
    Repository <|.. CategoryRepository~Category string~
    Repository <|.. MenuRepository~Menu string~
    Repository <|.. CustomizationAddonRepository~CustomizationAddon string~
